name: ivar_mobile_ads
description: A Flutter package for displaying customizable mobile advertisements
version: 0.0.21
homepage: https://github.com/ramezaniivar/ivar_mobile_ads
repository: https://github.com/ramezaniivar/ivar_mobile_ads

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  device_info_plus: ^11.3.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir/Vazirmatn-Black.ttf
          weight: 100
        - asset: assets/fonts/vazir/Vazirmatn-Bold.ttf
          weight: 200
        - asset: assets/fonts/vazir/Vazirmatn-ExtraBold.ttf
          weight: 300
        - asset: assets/fonts/vazir/Vazirmatn-ExtraLight.ttf
          weight: 400
        - asset: assets/fonts/vazir/Vazirmatn-Light.ttf
          weight: 500
        - asset: assets/fonts/vazir/Vazirmatn-Medium.ttf
          weight: 600
        - asset: assets/fonts/vazir/Vazirmatn-Regular.ttf
          weight: 700
        - asset: assets/fonts/vazir/Vazirmatn-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/vazir/Vazirmatn-Thin.ttf
          weight: 900
    - family: MingCute
      fonts:
        - asset: assets/fonts/MingCute.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
